#!/bin/sh

alias sudo="sudo "
alias vim="nvim" vimdiff="nvim -d"

alias r="make clean && make && make run"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	sdn="sudo shutdown -h now" \
	p="sudo pacman" \

# cd on quit for Vifm
f()
{
    local dst="$(command vifm --choose-dir - "$@")"
    if [ -z "$dst" ]; then
        echo 'Directory picking cancelled/failed'
        return 1
    fi
    cd "$dst"
}

# fzf - xdg-open file
o()
{
    fzf | awk '{printf("\"%s\"", $0);}' | xargs -r xdg-open;
}

# fzf - open file in vim
vo()
{
    fzf | awk '{printf("\"%s\"", $0);}' | xargs -r $EDITOR;
}

# fzf - xdg-open file, and cd
ocd()
{
    local filepath
    filepath=$(fzf)
    echo $filepath | awk '{printf("\"%s\"", $0);}' | xargs -r xdg-open;
    [[ ! -z $filepath ]] && cd "$(dirname "$filepath")"
}

# fzf - open file in vim, and cd
vocd()
{
    local filepath
    filepath=$(fzf)
    echo $filepath | awk '{printf("\"%s\"", $0);}' | xargs -r $EDITOR;
    [[ ! -z $filepath ]] && cd "$(dirname "$filepath")"
}

## fkill - kill process
## Similar to "kill -9 **" fzf default completion
fkill() {
    local pid
    pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
    echo $pid | xargs -r kill -${1:-9}
}
